### PR TITLE
feat: add support for Valkey users

### PR DESCRIPTION
**Pull request by bogdanp05**
With the release of [Aiven for Valkey](https://aiven.io/docs/products/valkey), it's possible to create Valkey ACL users via the API. This PR adds the required fields to `AccessControl`.

### CODE REVIEW

**Review by willyborankin — APPROVED** [review]

**Comment by byashimov** [comment]
Hey. Thanks for the contribution!
This change has been automatically delivered to the code-generated client https://github.com/aiven/go-client-codegen/commit/149e780284772c5cf5162556c57c6a99a735f7e8#diff-48bfae2c1b90bdc20b7ef17dedbbb4444f5b32c7881d651352aea137b9b812bcR531
Do you still need your changes in this rep? We try to not use this client, except exceptional cases :)

**Comment by bogdanp05** [comment]
@byashimov  Oh nice! I didn't know about the generated client. I have couple of follow-up questions:
- I see the aiven terraform provider uses both the generated client and this client. I'm guessing it's possible to add a resource for Valkey only with the generated client?
- Are we planning to deprecate this client eventually in favor of the generated one?

If the answer is yes for both questions, I can close this PR.

**Comment by byashimov** [comment]
Hey. We use both clients because there are parts of the API that still can't be generated. But, yes, we plan to deprecate this client. 
Regarding the terraform, unfortunately this part has no generation. Please make a ticket for that in jira. Thanks.

**Comment by bogdanp05** [comment]
Thanks, makes sense, closing.

**Pull request closed without merging**
