### PR TITLE
ci: update version.go in releaser github workflow

### LINKED ISSUE #307: version.go is not bumped during autorelease
currently, `version.go` is not getting bumped automatically during autorelease

the idea is to make it automated as well

### PR DESCRIPTION
**Pull request by rominf**
Resolve #307.

### CODE REVIEW

**Comment by rominf** [comment]
Tested in my fork, see the commit history: https://github.com/rominf/aiven-go-client/commits/main/.

**Review by Serpentiel — APPROVED** [review]
lgtm, good stuff

**Review by Serpentiel — CHANGES_REQUESTED** [review]
please make the generated commit compliant with the Conventional Commits

**Comment by rominf** [comment]
@Serpentiel I was not sure what to put as a prefix. Is:
```
chore(version.go): update aiven-go-client version
```
good enough?

**Pull request merged**
